#Pandas All Concepts

In [16]:
# importing pandas
import numpy as np
import pandas as pd

##Series made from Lists

In [17]:
# Series -> columns in the table are called series in pandas. Series is a class inside pandas.
country = ['India','Pakistan','China','Srilanka']
pd.Series(country)

# Notes: In pandas , when we get dtype: object , it means values are in string form. Not in everycase but most of the cases.
#        Series include two things: index and values
#        country is as object of 'Series' class

0       India
1    Pakistan
2       China
3    Srilanka
dtype: object

In [18]:
# integers
runs = [13,45,77,23,55]
pd.Series(runs)

0    13
1    45
2    77
3    23
4    55
dtype: int64

In [19]:
# custom index
marks = [67,69,99,10]
subjects = ['maths','science','english','french']

custom = pd.Series(marks,index=subjects)
print(custom)

maths      67
science    69
english    99
french     10
dtype: int64

In [20]:
# setting a name
y = pd.Series(marks,index=subjects,name='Marks of Mayank')
print(y)

maths      67
science    69
english    99
french     10
Name: Marks of Mayank, dtype: int64

##Series made from dictionary

In [21]:
marks = {
    'English':69,
    'Hindi':100,
    'Computer science':100
}

marks_dict = pd.Series(marks)
print(marks_dict)

English              69
Hindi               100
Computer science    100
dtype: int64

##Series Attributes

In [22]:
# size
marks_dict.size

3

In [23]:
y.size

4

In [24]:
# dtype
y.dtype

dtype('int64')

In [25]:
# name
y.name

'Marks of Mayank'

In [26]:
# is_unique -> tells about all the elements of the series are unique of not
y.is_unique

True

In [27]:
# index
y.index

Index(['maths', 'science', 'english', 'french'], dtype='object')

In [28]:
runs = pd.Series([13,45,77,23,55])
runs.index

# RangeIndex is just a special kind of object which store index values

RangeIndex(start=0, stop=5, step=1)

In [29]:
# values -> gives a numpy array
y.values

array([67, 69, 99, 10])

##Series using read_csv

In [36]:
# with 1 column
subs = pd.read_csv('/content/subs.csv')
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [67]:
# with 2 column
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
print(vk)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [34]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
print(movies)

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

##Series Methods

In [38]:
# head and tail
# head -> give data preview only , show first 5 rows from data by dafault BUT we can ask for more by mentioning no. of rows in head()

print(subs.head())

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [41]:
print(vk.tail())

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [47]:
# sample -> give one row from data randomly
# useful when our data has some bias
print(movies.sample(3))

                                          lead
movie
Love U...Mr. Kalakaar!          Tusshar Kapoor
Umrao Jaan (2006 film)  Aishwarya Rai Bachchan
The Stoneman Murders             Kay Kay Menon

In [50]:
# value_counts -> tells the frequency for a value present in data in DESC order
print(movies.value_counts())

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [55]:
# sort_values
print(vk.sort_values(by='runs',ascending=False))

          runs
match_no
128        113
126        109
123        108
120        100
164        100
...        ...
93           0
130          0
206          0
207          0
211          0

[215 rows x 1 columns]

In [62]:
# we can use head() here also
# THIS IS CALLED METHOD CHAINING
print(vk.sort_values(by='runs',ascending=False).head(3).values[0])

[113]

In [65]:
# if you want to do permanent changes in dataset , you have to use inplace=True
vk.sort_values(by='runs',inplace=True)

In [66]:
print(vk)

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [69]:
# sort_index
print(movies.sort_index())

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

##Series Maths Methods

In [75]:
# count -> give count of elements but dont consider missing values
# size -> do same work but consider missing values

print(vk.count())
print()
print(vk.size)

runs    215
dtype: int64

215

In [77]:
# sum
print(subs.sum())

Subscribers gained    49510
dtype: int64

In [79]:
# product
print(subs.product())

Subscribers gained    0
dtype: int64

In [80]:
# mean
print(subs.mean())

Subscribers gained    135.643836
dtype: float64

In [82]:
# median
print(vk.median())

runs    24.0
dtype: float64

In [84]:
# mode -> which value has highest frequency
print(movies.mode())

           lead
0  Akshay Kumar

In [85]:
# std (standard deviation)
print(subs.std())

Subscribers gained    62.675023
dtype: float64

In [86]:
# var (variance)
print(vk.var())

runs    688.002478
dtype: float64

In [87]:
# min/max
print(subs.min())

Subscribers gained    33
dtype: int64

In [89]:
# describe -> give summary
print(vk.describe())

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000